version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - mongo_data:/data/db

  # Node API service
  api:
    build:
      context: .
      dockerfile: Dockerfile # Assicurati di avere un Dockerfile nella directory
    container_name: api_container
    ports:
      - 3030:3030
    depends_on: 
      - mongo_db
    environment:
      MONGO_URL: mongodb://root:example@mongo_db:27017/dealershipsDB?authSource=admin
    command: ["npm", "start"] # Aggiungi il comando di avvio dell'applicazione Node.js

volumes:
  mongo_data: {}
